# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(default='Complete the game', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('complete_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('C', 'Complete')], default='N', max_length=1)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
        ),
    ]
