# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalassignment',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
        ),
    ]
