# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20151228_1623'),
        ('goals', '0002_auto_20151228_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Complete the game', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='goalassignment',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='complete_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 21, 23, 30, 897000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('C', 'Complete')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goals.GoalText'),
        ),
        migrations.DeleteModel(
            name='GoalAssignment',
        ),
        migrations.AddField(
            model_name='goal',
            name='progress_logs',
            field=models.ManyToManyField(to='goals.ProgressLog'),
        ),
    ]
