# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20151228_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_logs',
            field=models.ManyToManyField(blank=True, to='goals.ProgressLog'),
        ),
    ]
