# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20151228_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltext',
            name='text',
            field=models.CharField(default='Complete the game', max_length=400, unique=True),
        ),
    ]
