# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20151228_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
