# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20151230_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltext',
            name='id',
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.ForeignKey(default='Complete the game', on_delete=django.db.models.deletion.CASCADE, to='goals.GoalText'),
        ),
        migrations.AlterField(
            model_name='goaltext',
            name='text',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
