# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalassignment',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='game',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GoalAssignment',
        ),
    ]
