# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20151228_1548'),
        ('games', '0002_auto_20151228_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='goal',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='goals.GoalAssignment'),
        ),
    ]
