# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='goal',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
        ),
    ]
