# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20151228_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='id',
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
