# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160102_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='generation',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
