# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_console_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(default="There's no description for this genre yet.", max_length=500),
        ),
    ]
