# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamebeaterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_status', models.CharField(choices=[('W', 'Wants'), ('B', 'Borrows'), ('P', 'Owns Physically'), ('V', 'Owns Virtually')], default='W', max_length=1)),
                ('completion_status', models.CharField(choices=[(b'N', b'Not Started'), (b'I', b'In Progress'), (b'O', b'On Hold'), (b'C', b'Complete')], default=b'N', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.GamebeaterProfile')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('complete_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[(b'N', b'Not Started'), (b'I', b'In Progress'), (b'O', b'On Hold'), (b'C', b'Complete')], default=b'N', max_length=1)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.GameOwnership')),
            ],
        ),
        migrations.AddField(
            model_name='gamebeaterprofile',
            name='games',
            field=models.ManyToManyField(through='profiles.GameOwnership', to='games.Game'),
        ),
        migrations.AddField(
            model_name='gamebeaterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
